config/routes.rb
Spree::Core::Engine.routes.append do
  
  scope(:module => "blogs") do
  #scope module: 'spree' do

    namespace :admin do
      
      resources :blogs, :constraints => { :id => /[a-z0-9\-\_\/]{3,}/ }
      
      resources :posts do 
        resources :images,   :controller => "post_images" do
          collection do
            post :update_positions
          end
        end
        resources :products, :controller => "post_products"
        resources :categories, :controller => "post_categories"
      end
      
      resource :disqus_settings
      
    end
     
    constraints :blog_id => /([a-z0-9\-\_\/]{3,})/ do
      
      constraints(
        :year  => /\d{4}/,
        :month => /\d{1,2}/,
        :day   => /\d{1,2}/
      ) do 
        get ":blog_id/:year(/:month(/:day))" => "posts#index", :as => :post_date
        get ":blog_id/:year/:month/:day/:id" => "posts#show",  :as => :full_post
      end
      
      get ":blog_id/category/:id"   => "post_categories#show", :as => :post_category, :constraints => { :id => /.*/ }
      get ":blog_id/search/:query"  => "posts#search",         :as => :search_posts, :query => /.*/
      get ":blog_id/archive"        => "posts#archive",        :as => :archive_posts
      get ":blog_id"                => "posts#index",          :as => :blog_posts
    
    end
    
  end

end

app/models/spree/blog.rb
class Spree::Blog < ActiveRecord::Base
  
  attr_accessible :name, :permalink
  
  RESERVED_PATHS = /(^\/*(admin|account|cart|checkout|content|login|pg|orders|products|s|session|signup|shipments|states|t|tax_categories|user)\/+)/
  
  has_many :posts, :class_name => "Spree::Post", :dependent => :destroy
  has_many :categories, :through => :posts, :source => :post_categories, :uniq => true
  
  validates :name, :presence => true
  validates :permalink, :uniqueness => true, :format => { :with => /^[a-z0-9\-\_\/]+$/i }, :length => { :within => 3..40 }
  validate  :permalink_availablity
  
  before_validation :normalize_permalink
  
  def self.find_by_permalink!(path)
    super path.to_s.gsub(/(^\/+)|(\/+$)/, "")
  end

  def self.find_by_permalink(path)
    find_by_permalink!(path) rescue ActiveRecord::RecordNotFound
  end
  
  def self.to_options
    self.order(:name).map{|i| [ i.name, i.id ] }
  end
  
  def to_param
    self.permalink.gsub(/(^\/+)|(\/+$)/, "")
  end
  
private

  def permalink_availablity
    errors.add(:permalink, "is reserved, please try another.") if "/#{permalink}/" =~ RESERVED_PATHS
  end

  def normalize_permalink
    #self.permalink = (permalink.blank? ? name.to_s.parameterize : permalink).downcase.gsub(/(^[\/\-\_]+)|([\/\-\_]+$)/, "")
    self.permalink = (permalink.blank? ? name.to_s.to_url : permalink).downcase.gsub(/(^[\/\-\_]+)|([\/\-\_]+$)/, "")
  end
  
end

app/controllers/spree/blogs/admin/blogs_controller.rb
class Spree::Blogs::Admin::BlogsController < Spree::Admin::ResourceController

  def show
    redirect_to admin_blogs_path
  end
  
private
  
  def find_resource
    Spree::Blog.find_by_permalink!(params[:id])
  end  
    
  def collection
    params[:search] ||= {}
    params[:search][:meta_sort] ||= "name.asc"
    @search = Spree::Blog.search(params[:q])
    @collection = @search.result.page(params[:page]).per(Spree::Config[:orders_per_page])
  end

end

app/controllers/spree/blogs/admin/disqus_settings_controller.rb
class Spree::Blogs::Admin::DisqusSettingsController < Spree::Admin::BaseController

  def show
    @preferences = ['disqus_shortname']
    @config = Spree::BlogConfiguration.new
  end

  def edit
    @preferences = ['disqus_shortname']
    @config = Spree::BlogConfiguration.new
  end

  def update
    config = Spree::BlogConfiguration.new

    params.each do |name, value|
      next unless config.has_preference? name
      config[name] = value
    end

    redirect_to admin_disqus_settings_path
  end

end

app/controllers/spree/blogs/admin/post_categories_controller.rb
class Spree::Blogs::Admin::PostCategoriesController < Spree::Admin::ResourceController
  
  before_filter :load_data

  private

    def location_after_save
      admin_post_categories_url(@post)
    end
      
    def load_data
      @post = Spree::Post.find_by_path(params[:post_id])
      @post_categories = Spree::PostCategory.all
    end
  
end

app/controllers/spree/blogs/admin/post_images_controller.rb
class Spree::Blogs::Admin::PostImagesController < Spree::Admin::ResourceController
  
  before_filter :load_data

  create.before :set_viewable
  update.before :set_viewable
  destroy.before :destroy_before

  def update_positions
    params[:positions].each do |id, index|
      Spree::PostImage.update_all(['position=?', index], ['id=?', id])
    end

    respond_to do |format|
      format.js  { render :text => 'Ok' }
    end
  end
  
  private
  
  def location_after_save
    admin_post_images_url(@post)
  end

  def load_data
    @post = Spree::Post.find_by_path(params[:post_id])
  end

  def set_viewable
    @post_image.viewable = @post
  end

  def destroy_before
    @viewable = @post_image.viewable
  end

end

app/controllers/spree/blogs/admin/post_products_controller.rb
class Spree::Blogs::Admin::PostProductsController < Spree::Admin::BaseController
  
  before_filter :load_data
  
  def create
    position = @post.products.count
    @product = Spree::Variant.find(params[:variant_id]).product
    Spree::PostProduct.create(:post_id => @post.id, :product_id => @product.id, :position => position)
    render :partial => "spree/blogs/admin/post_products/related_products_table", :locals => { :post => @post }, :layout => false
  end
    
  def destroy
    @related = Spree::PostProduct.find(params[:id])
    if @related.destroy
      render_js_for_destroy
    end
  end
    
  private
  
    def load_data
	  	@post = Spree::Post.find_by_path(params[:post_id])
      #@post = Spree::Post.find(params[:post_id])
    end

end

app/controllers/spree/blogs/admin/posts_controller.rb
class Spree::Blogs::Admin::PostsController < Spree::Admin::ResourceController

  update.before :set_category_ids
  
  def new
    @post = Spree::Post.new
    @post.posted_at ||= Time.now
  end

private
  
  def set_category_ids
    if params[:post] && params[:post][:post_category_ids].is_a?(Array)
      params[:post][:post_category_ids].reject!{|i| i.to_i == 0 }
    end
  end
  
  def location_after_save
    path = params[:redirect_to].to_s.strip.sub(/^\/+/, "/")
    path.blank? ? object_url : path
  end 
  
  def find_resource
  	@object ||= Spree::Post.find_by_path(params[:id])
  end
  
  def collection
    params[:search] ||= {}
    params[:search][:meta_sort] ||= "posted_at.desc"
    @search = Spree::Post.search(params[:q])
    @collection = @search.result.order('posted_at DESC').page(params[:page]).per(Spree::Config[:orders_per_page])
  end

end

app/controllers/spree/blogs/post_categories_controller.rb
class Spree::Blogs::PostCategoriesController < Spree::BaseController
  
  include SpreeEssentialBlog::PostsControllerHelper

  before_filter :get_sidebar, :only => [:index, :search, :show]
  
  def show
    @category = Spree::PostCategory.find_by_permalink(params[:id])
    @posts = @category.posts.live
    @posts = @posts.page(params[:page]).per(Spree::Post.per_page)
  end
  
end

app/controllers/spree/blogs/posts_controller.rb
class Spree::Blogs::PostsController < Spree::BaseController

  include SpreeEssentialBlog::PostsControllerHelper

  helper "spree/products"
  
  before_filter :get_sidebar, :only => [:index, :search, :show]
  
  def index
    @posts_by_month = default_scope.order('posted_at DESC').limit(50).group_by { |post| post.posted_at.strftime("%B %Y") }
    scope = default_scope.order('posted_at DESC')
    if params[:year].present?
      year  = params[:year].to_i
      month = 1
      day   = 1  
      if has_month = params[:month].present?
        if has_day = params[:day].present?
          day  = params[:day].to_i
        end
        month = params[:month].to_i
      end
      start = Date.new(year, month, day)
      stop  = start + 1.year
      if has_month
        stop = start + 1.month
        if has_day
          stop = start + 1.day
        end
      end    
      scope = scope.where("posted_at >= ? AND posted_at <= ?", start, stop)
    end
    @posts = scope.page(params[:page]).per(Spree::Post.per_page)
  end
  # tag search
  def search
		query = params[:query].gsub(/%46/, '.')	
		@posts = default_scope.tagged_with(query).order('posted_at DESC').page(params[:page]).per(Spree::Post.per_page)
		get_tags		
		render :template => 'spree/blogs/posts/index'
	end
	
  def show
    @post = default_scope.includes(:tags, :images, :products).find_by_path(params[:id]) rescue nil
    return redirect_to archive_posts_path unless @post
  end
  
	def archive
		@posts = default_scope.all
  end
  
end

app/helpers/spree/blogs/posts_helper.rb
module Spree::Blogs::PostsHelper

  def post_seo_path(blog, post)
    spree.full_post_path(blog, post.year, post.month, post.day, post.to_param)
  end

  def post_seo_url(blog, post)
    spree.full_post_url(blog, post.year, post.month, post.day, post.to_param)
  end

  def post_rss(post)
    output = []
    post.images.each do |image|
      output << image_tag(image.attachment.url, :alt => image.alt)
    end
    output << post.rendered_body
    output.join("\n").html_safe
  end

end

app/views/spree/blogs/shared/_archive.html.erb
<div class="post-archive">
  <% posts.group_by(&:year).each do |year, posts_by_year| %>
    <h4 class="year"><%= link_to year, post_date_path(@blog, year) %></h4>
    <% index = 0 %>
    <% posts_by_year.group_by(&:month).each do |month, posts_by_month| %>
      <div class="month<%= ' alt' if (index += 1) % 2 == 0 %>">
        <h5 class="month"><%= link_to l(Date.new(year, month), :format => :month_year, :use_standalone_month_names => true ), post_date_path(@blog, year, month) %></h5>
        <ul class="archive">
          <% posts_by_month.group_by(&:day).each do |day, posts_by_day| %>
            <li>
              <span class="day">
                <%= link_to day, post_date_path(@blog, year, month, day) %>
              </span>
              <ul class="posts">
                <% posts_by_day.each_with_index do |post, index| %>
                  <li><%= link_to h(post.title), post_seo_path(@blog, post) %></li>
                <% end %>
              </ul>
              <br class="clear"/>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <br class="clear"/>
  <% end %>
</div>

app/views/spree/blogs/shared/_disqus_comments.html.erb
<% disqus_short_name = ::SpreeEssentialBlog::Config.preferred_disqus_shortname %>
<% if !disqus_short_name.blank? %>
  <div class="post-comments">
    <h3><%= t('spree.blogs.comments') %></h3>
    <div id="disqus_thread"></div>
    <script type="text/javascript">
        var disqus_shortname = <%== disqus_short_name.inspect %>;
        var disqus_identifier = <%== @post.path.inspect %>;
        var disqus_url = <%== request.url.inspect %>;
        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
  </div>
<% end %>

app/views/spree/blogs/shared/_preview.html.erb
<div class="post-preview"  data-hook="post-preview">

  <div class="post-title"  data-hook="post-title">
    <h2><%= link_to h(post.title), post_seo_path(@blog, post) %></h2>
    <h5><%= l post.posted_at, :format => :date_full %></h5>
  </div>

  <% if post.has_images? %>
    <p class="post-images"><%= link_to image_tag(post.images.first.attachment.url, :alt => post.title), post_seo_path(@blog, post) %></p>
  <% end %>

  <%= post.rendered_preview %>

  <br class="clear" />

  <p><%= link_to t('.read_more'), post_seo_path(@blog, post) %></p>

</div>

app/views/spree/blogs/shared/_sidebar.html.erb
<div class="post-sidebar" data-hook="post-sidebar">

  <h3><%= t('.recent_posts') %></h3>  
  <%= render 'spree/blogs/shared/archive', :posts => @archive_posts %>
  
  <p class="more"><%= link_to t('.view_archive'), archive_posts_path(@blog) %></p>
  
  <div class="post-categories" data-hook="post-categories">
    <h3><%= t('.categories') %></h3>
    <ul>
      <% @post_categories.each do |category| %>
        <li><%= link_to category.name, post_category_path(@blog, category.permalink) %></li>
      <% end %>
    </ul>
  </div>
  
  <div class="tag-cloud" data-hook="post-tag-cloud">
    <h3><%= t('.tags') %></h3>
    <ul class="tags">
      <% tag_cloud @tags, %w(neat cool rad awesome) do |tag, css_class| %>
        <li><%= link_to tag.name, search_posts_path(@blog, tag.name), :class => css_class %></li>
      <% end %>
    </ul>
  </div>
  
</div>