config/routes.rb
Spree::Core::Engine.routes.append do
  
  scope(:module => "blogs") do
  #scope module: 'spree' do

    namespace :admin do
      
      resources :blogs, :constraints => { :id => /[a-z0-9\-\_\/]{3,}/ }
      
      resources :posts do 
        resources :images,   :controller => "post_images" do
          collection do
            post :update_positions
          end
        end
        resources :products, :controller => "post_products"
        resources :categories, :controller => "post_categories"
      end
      
      resource :disqus_settings
      
    end
     
    constraints :blog_id => /([a-z0-9\-\_\/]{3,})/ do
      
      constraints(
        :year  => /\d{4}/,
        :month => /\d{1,2}/,
        :day   => /\d{1,2}/
      ) do 
        get ":blog_id/:year(/:month(/:day))" => "posts#index", :as => :post_date
        get ":blog_id/:year/:month/:day/:id" => "posts#show",  :as => :full_post
      end
      
      get ":blog_id/category/:id"   => "post_categories#show", :as => :post_category, :constraints => { :id => /.*/ }
      get ":blog_id/search/:query"  => "posts#search",         :as => :search_posts, :query => /.*/
      get ":blog_id/archive"        => "posts#archive",        :as => :archive_posts
      get ":blog_id"                => "posts#index",          :as => :blog_posts
    
    end
    
  end

end

app/views/spree/blogs/admin/shared/_blog_config.html.erb
<tr>
  <td><%= link_to t("spree.blogs.settings.blogs"), admin_blogs_path %></td>
  <td><%= t("spree.blogs.settings.explain_blogs") %></td>
</tr>
<tr>
  <td><%= link_to t("spree.blogs.settings.disqus"), edit_admin_disqus_settings_path %></td>
  <td><%= t("spree.blogs.settings.explain_disqus") %></td>
</tr>

app/views/spree/blogs/admin/shared/_post_tabs.html.erb
<h1><%== t(".editing_post") + " &ldquo;#{@post.title}&rdquo;".html_safe %></h1>

<% content_for :sidebar do %>

  <h3 class="name"><%= @post.title %><span class='sku'><%= l (@post.posted_at || Time.now), :format => :date_only %></span></h3>
  <br clear="clear" />

  <ul class="sidebar post-menu">
    <li<%= ' class="active"'.html_safe if current == "Post Details" %>>
      <%= link_to t(".post_details"), edit_admin_post_url(@post) %>
    </li>
    <li<%= ' class="active"'.html_safe if current == "Images" %>>
      <%= link_to t("images"), admin_post_images_url(@post) %>
    </li>
    <li<%= ' class="active"'.html_safe if current == "Related Products" %>>
      <%= link_to t(".related_products"), admin_post_products_url(@post) %>
    </li>
    <li<%= ' class="active"'.html_safe if current == "Categories" %>>
      <%= link_to t(".post_categories"), admin_post_categories_url(@post) %>
    </li>
  </ul>
  <br clear="clear" />

<% end %>

app/views/spree/blogs/admin/shared/_select_configuration_tab.html.erb
<% content_for :head do %>
  <script type="text/javascript">
    jQuery(document).ready(function(){
      jQuery("#admin-menu li:contains(Configuration)").addClass("selected");
    });
  </script>
<% end %>