config/routes.rb
Spree::Core::Engine.routes.append do
  
  scope(:module => "blogs") do
  #scope module: 'spree' do

    namespace :admin do
      
      resources :blogs, :constraints => { :id => /[a-z0-9\-\_\/]{3,}/ }
      
      resources :posts do 
        resources :images,   :controller => "post_images" do
          collection do
            post :update_positions
          end
        end
        resources :products, :controller => "post_products"
        resources :categories, :controller => "post_categories"
      end
      
      resource :disqus_settings
      
    end
     
    constraints :blog_id => /([a-z0-9\-\_\/]{3,})/ do
      
      constraints(
        :year  => /\d{4}/,
        :month => /\d{1,2}/,
        :day   => /\d{1,2}/
      ) do 
        get ":blog_id/:year(/:month(/:day))" => "posts#index", :as => :post_date
        get ":blog_id/:year/:month/:day/:id" => "posts#show",  :as => :full_post
      end
      
      get ":blog_id/category/:id"   => "post_categories#show", :as => :post_category, :constraints => { :id => /.*/ }
      get ":blog_id/search/:query"  => "posts#search",         :as => :search_posts, :query => /.*/
      get ":blog_id/archive"        => "posts#archive",        :as => :archive_posts
      get ":blog_id"                => "posts#index",          :as => :blog_posts
    
    end
    
  end

end

app/models/spree/post_image.rb
class Spree::PostImage < Spree::Asset

  attr_accessible :alt, :attachment

  validates_attachment_presence :attachment

  has_attached_file :attachment,
    :styles => Proc.new{ |clip| clip.instance.attachment_sizes },
    :default_style => :medium,
    :url => '/spree/posts/:id/:style/:basename.:extension',
    :path => ':rails_root/public/spree/posts/:id/:style/:basename.:extension'

  def image_content?
    attachment_content_type.to_s.match(/\/(jpeg|png|gif|tiff|x-photoshop)/)
  end
  
  def attachment_sizes
    hash = {}
    hash.merge!(:mini => '48x48>', :small => '150x150>', :medium => '600x600>', :large => '950x700>') if image_content?
    hash
  end
    
end

app/controllers/spree/blogs/admin/post_images_controller.rb
class Spree::Blogs::Admin::PostImagesController < Spree::Admin::ResourceController
  
  before_filter :load_data

  create.before :set_viewable
  update.before :set_viewable
  destroy.before :destroy_before

  def update_positions
    params[:positions].each do |id, index|
      Spree::PostImage.update_all(['position=?', index], ['id=?', id])
    end

    respond_to do |format|
      format.js  { render :text => 'Ok' }
    end
  end
  
  private
  
  def location_after_save
    admin_post_images_url(@post)
  end

  def load_data
    @post = Spree::Post.find_by_path(params[:post_id])
  end

  def set_viewable
    @post_image.viewable = @post
  end

  def destroy_before
    @viewable = @post_image.viewable
  end

end

app/views/spree/blogs/admin/post_images/_form.html.erb
<p>
  <%= form.label :attachment %>:<br/>
  <%= form.file_field :attachment %>
</p>
<p>
  <%= form.label :alt %>:<br/>
  <%= form.text_field :alt, :class => 'text' %>
</p>

app/views/spree/blogs/admin/post_images/edit.html.erb
<%= render :partial => 'spree/blogs/admin/shared/post_tabs', :locals => {:current => "Images"} %>

<% if @post_image.try(:errors).present? %>
  <%= render 'spree/shared/error_messages', :target => @post_image %>
<% end %>

<%= form_for([:admin, @post.id, @post_image], :url => admin_post_image_url(@post, @post_image), :html => { :multipart => true }) do |f| %>
    <p>
      <%= label_tag ("thumbnail") %>:<br/>
      <%= link_to(image_tag(@post_image.attachment.url(:mini)), @post_image.attachment.url(:product)) %>
    </p>
    <%= render "form", :form => f %>
  </table>
  <p class="form-buttons">
    <%= button t("update") %>
    or <%= link_to t("cancel"), admin_post_images_url(@post), :id => "cancel_link" %>
  </p>
<% end %>

app/views/spree/blogs/admin/post_images/index.html.erb
<%= render :partial => 'spree/blogs/admin/shared/post_tabs', :locals => {:current => "Images"} %>

<table class="index sortable" data-sortable-link="<%= update_positions_admin_post_images_url(@post) -%>">
  <thead>
    <tr>
      <th><%= t("thumbnail") %></th>
      <th><%= t("alt_text") %></th>
      <th><%= t("action") %></th>
    </tr>
  </thead>
  <tbody>
    <% @post.images.each do |image| %>
      <tr id="<%= dom_id(image) %>">
        <td><span class="handle">&nbsp;</span>&nbsp; <%= link_to(image_tag(image.attachment.url(:mini)), image.attachment.url(:large)) %></td>
        <td><%= image.alt %></td>
        <td class="actions">
          <%= link_to_with_icon('edit', t("edit"), edit_admin_post_image_url(@post, image)) %>
          &nbsp;
          <%= link_to_delete image, {:url => admin_post_image_url(@post, image) }%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div id="images"></div>
<br/>
<p>
    <%= link_to icon('add') + ' ' + t("new_image"), new_admin_post_image_url(@post), :id => "new_image_link" %>
</p>

<% content_for :head do %>
  <script type="text/javascript">
    jQuery(document).ready(function(){

      jQuery('#new_image_link').click(function (event) {
        event.preventDefault();
        jQuery(this).hide();
        jQuery.ajax({type: 'GET', url: this.href, data: ({authenticity_token: AUTH_TOKEN}), success: function(r){ jQuery('#images').html(r);} });
      });

    });
  </script>
<% end %>

app/views/spree/blogs/admin/post_images/new.html.erb
<%= render :partial => 'spree/blogs/admin/shared/post_tabs', :locals => {:current => "Images"} unless request.xhr? %>

<h3><%= t("new_image") %></h3>

<%= render 'spree/shared/error_messages', :target => @post_image %>

<%= form_for(@post_image, :url => admin_post_images_path(@post), :html => { :multipart => true }) do |form| %>
  <table class="basic-table">
    <%= render "form", :form => form %>
  </table>
  <p class="form-buttons">
    <%= button t("create") %>
    or <%= link_to t("cancel"), "#", :id => "cancel_link" %>
  </p>
<% end %>

<script type="text/javascript">    
  jQuery('#cancel_link').click(function (event) { 
    jQuery('#new_image_link').show();
    jQuery('#images').html('');
  }); 
</script>