config/routes.rb
Spree::Core::Engine.routes.append do
  
  scope(:module => "blogs") do
  #scope module: 'spree' do

    namespace :admin do
      
      resources :blogs, :constraints => { :id => /[a-z0-9\-\_\/]{3,}/ }
      
      resources :posts do 
        resources :images,   :controller => "post_images" do
          collection do
            post :update_positions
          end
        end
        resources :products, :controller => "post_products"
        resources :categories, :controller => "post_categories"
      end
      
      resource :disqus_settings
      
    end
     
    constraints :blog_id => /([a-z0-9\-\_\/]{3,})/ do
      
      constraints(
        :year  => /\d{4}/,
        :month => /\d{1,2}/,
        :day   => /\d{1,2}/
      ) do 
        get ":blog_id/:year(/:month(/:day))" => "posts#index", :as => :post_date
        get ":blog_id/:year/:month/:day/:id" => "posts#show",  :as => :full_post
      end
      
      get ":blog_id/category/:id"   => "post_categories#show", :as => :post_category, :constraints => { :id => /.*/ }
      get ":blog_id/search/:query"  => "posts#search",         :as => :search_posts, :query => /.*/
      get ":blog_id/archive"        => "posts#archive",        :as => :archive_posts
      get ":blog_id"                => "posts#index",          :as => :blog_posts
    
    end
    
  end

end

app/models/spree/post_category.rb
class Spree::PostCategory < ActiveRecord::Base
  
  attr_accessible :name, :permalink
  
  validates :name, :presence => true
  validates :permalink,  :presence => true, :uniqueness => true, :if => proc{ |record| !record.name.blank? }
  
  has_and_belongs_to_many :posts, :join_table => 'spree_post_categories_posts', :uniq => true
  
  before_validation :create_permalink
  
  def to_param
    permalink
  end
  
  private
  
    def create_permalink
      count = 2
      #new_permalink = name.to_s.parameterize
      new_permalink = permalink.blank? ? name.to_s.to_url.parameterize : permalink.to_s.parameterize 
      exists = permalink_exists?(new_permalink)
      while exists do
        dupe_permalink = "#{new_permalink}_#{count}"
        exists = permalink_exists?(dupe_permalink)
        count += 1
      end
      self.permalink = dupe_permalink || new_permalink
    end
  
    def permalink_exists?(new_permalink)
      post_category = Spree::PostCategory.find_by_permalink(new_permalink)
      post_category != nil && !(post_category == self)
    end
    
end

app/controllers/spree/blogs/admin/post_categories_controller.rb
class Spree::Blogs::Admin::PostCategoriesController < Spree::Admin::ResourceController
  
  before_filter :load_data

  private

    def location_after_save
      admin_post_categories_url(@post)
    end
      
    def load_data
      @post = Spree::Post.find_by_path(params[:post_id])
      @post_categories = Spree::PostCategory.all
    end
  
end

app/controllers/spree/blogs/post_categories_controller.rb
class Spree::Blogs::PostCategoriesController < Spree::BaseController
  
  include SpreeEssentialBlog::PostsControllerHelper

  before_filter :get_sidebar, :only => [:index, :search, :show]
  
  def show
    @category = Spree::PostCategory.find_by_permalink(params[:id])
    @posts = @category.posts.live
    @posts = @posts.page(params[:page]).per(Spree::Post.per_page)
  end
  
end

app/views/spree/blogs/admin/post_categories/_form.html.erb
<p>
  <%= form.label :name, t("activerecord.attributes.post_category.name") %>:<br/>
  <%= form.text_field :name, :class => 'text' %>
</p>
<p>
  <%= form.label :permalink, t("activerecord.attributes.post_category.permalink") %>:<br/>
  <%= form.text_field :permalink, :class => 'text' %>
</p>

app/views/spree/blogs/admin/post_categories/edit.html.erb
<%= render :partial => 'spree/blogs/admin/shared/post_tabs', :locals => {:current => "Categories"} %>

<h3><%= t(".edit_category") %></h3>

<% if @post_category.try(:errors).present? %>
  <%= render 'spree/shared/error_messages', :target => @post_category %>
<% end %>

<%= form_for([:admin, @post, @post_category], :url => admin_post_category_path(@post, @post_category.id)) do |form| %>
  <%= render "form", :form => form %>
  <p class="form-buttons">
    <%= hidden_field_tag :post_id, @post.path, :class => 'hidden' %>
    <%= button t("update") %>
  </p>
<% end %>

app/views/spree/blogs/admin/post_categories/index.html.erb
<%= render :partial => 'spree/blogs/admin/shared/post_tabs', :locals => {:current => "Categories"} %>

<div id="categories-box">
  <%= form_for([:admin, @post]) do |f| %>
    <fieldset>
      <legend><%= t('.manage_categories') %></legend>
      <table class="index">
        <% @post_categories.each_with_index do |category, index| -%>
          <tr id="<%= dom_id(category) %>" class="<%= index % 2 == 0 ? 'alt' : 'row' %>">
            <td>
              <%= check_box_tag "post[post_category_ids][]", category.id, @post.post_categories.include?(category), :id => "post_category_id_#{index}" -%>
              <%= label_tag "post_category_id_#{index}", category.name -%>
            </td>
            <td class="options" style="width: 120px">
              <%= link_to_with_icon('edit', t("edit"), edit_admin_post_category_url(@post, category.id)) %> &nbsp;
              <%= link_to_delete category, {:url => admin_post_category_url(@post, category.id)} %>
            </td>
          </tr>
        <% end -%>
      </table>
      <%= hidden_field_tag "post[post_category_ids][]", 0 %>
      <%= hidden_field_tag :redirect_to, request.fullpath %>
      <%= button t("update") %>
    </fieldset>
  <% end %>
</div>
  
<div id="new_category"></div>
  
<p><%= link_to icon('add') + ' ' + t("new_category"), new_admin_post_category_url(@post), :id => "btn_new_category" %></p>
  

<% content_for :head do %>
  <script type="text/javascript">
    jQuery(document).ready(function(){  
      
      jQuery('#btn_new_category').click(function (event) { 
        event.preventDefault();
        jQuery(this).hide();
        jQuery.ajax({type: 'GET', url: this.href, data: ({authenticity_token: AUTH_TOKEN}), success: function(r){ jQuery('#new_category').html(r);} });
      });
      
    });
  </script>
<% end %>

app/views/spree/blogs/admin/post_categories/new.html.erb
<%= render :partial => 'spree/blogs/admin/shared/post_tabs', :locals => {:current => "Categories"} unless request.xhr? %>

<h3><%= t("new_category") %></h3>

<% if @post_category.try(:errors).present? %>
  <%= render 'spree/shared/error_messages', :target => @post_category %>
<% end %>

<%= form_for(@post_category, :url => admin_post_categories_path(@post)) do |form| %>
  <%= render "form", :form => form %>
  <p class="form-buttons">
    <%= button t("create") %>
  </p>
<% end %>